
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google"; // Noto Sans'ı içe aktar
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import type { Viewport } from "next";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], 
});

export const metadata: Metadata = {
  title: {
    default: `Pakettlyukle`,
    template: `%s - Pakettlyukle`,
  },
  description: "Generated by tDiff",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};



export default function RootLayout({

  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={`${notoSans.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
        
      </body>
      
    </html>
  );
}
