import React from 'react'
import Demo from "./demo";
import { Metadata } from "next";

export const metadata: Metadata = {
  description: "Generated by tDiff",
};

const page = () => {
  return (
    <div>
      <Demo />
    </div>
  )
}

export default page
