import React from 'react'
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: `Kurumsal`,
  description: "Generated by tDiff",
};

const KurumsalPage = () => {
  return (
    <div>
      kurumsal
    </div>
  )
}

export default KurumsalPage
